# Data Cleaning
Raw data can be downloaded from: https://www.kaggle.com/shuyangli94/food-com-recipes-and-user-interactions

In [1]:
import pandas as pd
import numpy as np
import os
import shutil
from IPython.display import display
from ast import literal_eval

In [2]:
raw_path = r'../00_Raw Data'
clean_path = r''
product_path = r'../05_RecipeExplorationTool/data'

# users_in
Input: PP_users.csv 

Output: |---user_id---|---recipe_id---|---rating---|

In [3]:
if os.path.exists(raw_path+"/PP_users.parquet"):
    pp_users = pd.read_parquet(raw_path+"/PP_users.parquet")
else: 
    yn = input("Do you want to read + interpret csv file? (y or n): ") # Raw data has lists in cells which is read in as a string, parsing to a list can take some time
    if yn == 'y':
        cols = ["techniques","items","ratings"]
        conv_dict = {c:literal_eval for c in cols}
        pp_users = pd.read_csv(raw_path+"/PP_users.csv",converters=conv_dict,engine='c')
        pp_users.to_parquet(raw_path+"/PP_users.parquet", index=False)

pp_users.head()

,u,techniques,items,n_items,ratings,n_ratings
0,0,"[8, 0, 0, 5, 6, 0, 0, 1, 0, 9, 1, 0, 0, 0, 1, ...","[1118, 27680, 32541, 137353, 16428, 28815, 658...",31,"[5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 4.0, 4.0, ...",31
1,1,"[11, 0, 0, 2, 12, 0, 0, 0, 0, 14, 5, 0, 0, 0, ...","[122140, 77036, 156817, 76957, 68818, 155600, ...",39,"[5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, ...",39
2,2,"[13, 0, 0, 7, 5, 0, 1, 2, 1, 11, 0, 1, 0, 0, 1...","[168054, 87218, 35731, 1, 20475, 9039, 124834,...",27,"[3.0, 4.0, 4.0, 4.0, 4.0, 4.0, 4.0, 4.0, 5.0, ...",27
3,3,"[498, 13, 4, 218, 376, 3, 2, 33, 16, 591, 10, ...","[163193, 156352, 102888, 19914, 169438, 55772,...",1513,"[5.0, 5.0, 5.0, 5.0, 4.0, 4.0, 5.0, 5.0, 5.0, ...",1513
4,4,"[161, 1, 1, 86, 93, 0, 0, 11, 2, 141, 0, 16, 0...","[72857, 38652, 160427, 55772, 119999, 141777, ...",376,"[5.0, 5.0, 5.0, 5.0, 4.0, 4.0, 5.0, 4.0, 5.0, ...",376

In [4]:
dfUser = pp_users[['u','items','ratings']].rename(columns={'items':'recipe_id', 'u':'user_id'})
users_in = dfUser.set_index('user_id').apply(pd.Series.explode).set_index('recipe_id',append=True)
assert np.sum(pp_users['ratings'].str.len()) == len(users_in)
display(users_in.head())
yn = input('Save users_in dataframe to clean data? (y or n): ')
if yn == 'y': 
    if os.path.isfile(os.path.join(clean_path,'users_in.csv')):
        i = 1
        while os.path.isfile(os.path.join(clean_path,'archive','users_in_v'+str(i)+".csv")):
            i+=1
        
        shutil.copyfile(os.path.join(clean_path,'users_in.csv'), os.path.join(clean_path,'archive','users_in_v'+str(i)+".csv"))
    users_in.to_csv(os.path.join(clean_path, 'users_in.csv'))

                  ratings
user_id recipe_id
0       1118            5
        27680           5
        32541           5
        137353          5
        16428           5

## users_in_filtered
Filter recipes used to only contain those with user positive user interaction

In [5]:
rating_count = 2 # Filter will remove recipe with less than rating_count reviews
rating_mean = 4 # Filter will remove reicpes with less than 4 star avg reviews

users_in = pd.read_csv(os.path.join(clean_path, 'users_in.csv'), index_col = [0,1])
recipe_filt = users_in.reset_index().drop('user_id',axis=1).groupby('recipe_id').agg(['count','mean'])
recipe_filt.columns = ['_'.join(i) for i in recipe_filt.columns]
recipe_filt = recipe_filt.loc[np.logical_and(recipe_filt['ratings_count']>=rating_count, recipe_filt['ratings_mean']>=rating_mean),:].index.tolist()

print(f"Raw users_in length: {len(users_in)}")
users_in_filtered = users_in.loc[users_in.index.get_level_values(1).isin(recipe_filt),:]
print(f"Filtered (count >= {rating_count}, mean >= {rating_mean}) users_in length: {len(users_in_filtered)}")
display(users_in_filtered.head())

yn = input('Save users_in_filtered dataframe to clean data? (y or n): ')
if yn == 'y': 
    if os.path.isfile(os.path.join(clean_path,f'users_in_count{rating_count}_mean{rating_mean}.csv')):
        i = 1
        while os.path.isfile(os.path.join(clean_path,'archive',f'users_in_count{rating_count}_mean{rating_mean}_v{i}.csv')):
            i+=1
        
        shutil.copyfile(os.path.join(clean_path,f'users_in_count{rating_count}_mean{rating_mean}.csv'), os.path.join(clean_path,'archive',f'users_in_count{rating_count}_mean{rating_mean}_v{i}.csv'))
    users_in_filtered.to_csv(os.path.join(clean_path, f'users_in_count{rating_count}_mean{rating_mean}.csv'))
    users_in_filtered.to_csv(os.path.join(product_path, f'users_in_count{rating_count}_mean{rating_mean}.csv'))

Raw users_in length: 698901
Filtered (count >= 2, mean >= 4) users_in length: 599009

                   ratings
user_id recipe_id
0       1118           5.0
        27680          5.0
        32541          5.0
        137353         5.0
        16428          5.0

# recipes_in

Input: RAW_recipes & PP_recipes

Output: |---recipes_id---|---nutrition---|---minutes---|---techniques---|---cuisine---|---meal_of_day---|---ingredients---|

Note:
* techniques: ~ 53K (23%) of recipes do not have techniques - should be able to translate steps to techniques
* cuisine: ~129K (56%) of recipes do not have a cuisine
* meal_of_day: ~345K (20%) of recipes do not have a meal_of_day
* For cuisine and meal_of_day: as soon as value is found it is assigned
    * Values sorted in descending order of appearance so if multiple tags are found, most popular is assigned

In [6]:
if os.path.exists(raw_path+"/RAW_recipes.parquet"):
    raw_recipes = pd.read_parquet(raw_path+"/RAW_recipes.parquet")
else: 
    yn = input("Do you want to read + interpret csv file? (y or n): ")
    if yn == 'y':
        cols = ["tags","nutrition","steps",'ingredients']
        conv_dict = {c:literal_eval for c in cols}
        raw_recipes = pd.read_csv(raw_path+"/RAW_recipes.csv",converters=conv_dict,engine='c')
        raw_recipes.to_parquet(raw_path+"/RAW_recipes.parquet", index=False)

print('raw_recipes')
display(raw_recipes.head())

if os.path.exists(raw_path+"/PP_recipes.parquet"):
    pp_recipes = pd.read_parquet(raw_path+"/PP_recipes.parquet")
else: 
    yn = input("Do you want to read + interpret csv file? (y or n): ")
    if yn == 'y':
        cols = ["name_tokens","ingredient_tokens","step_tokens","techniques"]
        conv_dict = {c:literal_eval for c in cols}
        pp_recipes = pd.read_csv(raw_path+"/PP_recipes.csv",converters=conv_dict,engine='c')
        pp_recipes.to_parquet(raw_path+"/PP_recipes.parquet", index=False)

print('pp_recipes')
display(pp_recipes.head())

raw_recipes

,name,id,minutes,contributor_id,submitted,tags,nutrition,n_steps,steps,description,ingredients,n_ingredients
0,arriba baked winter squash mexican style,137739,55,47892,2005-09-16,"[60-minutes-or-less, time-to-make, course, mai...","[51.5, 0.0, 13.0, 0.0, 2.0, 0.0, 4.0]",11,"[make a choice and proceed with recipe, depend...",autumn is my favorite time of year to cook! th...,"[winter squash, mexican seasoning, mixed spice...",7
1,a bit different breakfast pizza,31490,30,26278,2002-06-17,"[30-minutes-or-less, time-to-make, course, mai...","[173.4, 18.0, 0.0, 17.0, 22.0, 35.0, 1.0]",9,"[preheat oven to 425 degrees f, press dough in...",this recipe calls for the crust to be prebaked...,"[prepared pizza crust, sausage patty, eggs, mi...",6
2,all in the kitchen chili,112140,130,196586,2005-02-25,"[time-to-make, course, preparation, main-dish,...","[269.8, 22.0, 32.0, 48.0, 39.0, 27.0, 5.0]",6,"[brown ground beef in large pot, add chopped o...",this modified version of 'mom's' chili was a h...,"[ground beef, yellow onions, diced tomatoes, t...",13
3,alouette potatoes,59389,45,68585,2003-04-14,"[60-minutes-or-less, time-to-make, course, mai...","[368.1, 17.0, 10.0, 2.0, 14.0, 8.0, 20.0]",11,[place potatoes in a large pot of lightly salt...,"this is a super easy, great tasting, make ahea...","[spreadable cheese with garlic and herbs, new ...",11
4,amish tomato ketchup for canning,44061,190,41706,2002-10-25,"[weeknight, time-to-make, course, main-ingredi...","[352.9, 1.0, 337.0, 23.0, 3.0, 0.0, 28.0]",5,"[mix all ingredients& boil for 2 1 / 2 hours ,...",my dh's amish mother raised him on this recipe...,"[tomato juice, apple cider vinegar, sugar, sal...",8

pp_recipes

,id,i,name_tokens,ingredient_tokens,steps_tokens,techniques,calorie_level,ingredient_ids
0,424415,23,"[40480, 37229, 2911, 1019, 249, 6878, 6878, 28...","[[2911, 1019, 249, 6878], [1353], [6953], [153...","[40480, 40482, 21662, 481, 6878, 500, 246, 161...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, ...",0,"[389, 7655, 6270, 1527, 3406]"
1,146223,96900,"[40480, 18376, 7056, 246, 1531, 2032, 40481]","[[17918], [25916], [2507, 6444], [8467, 1179],...","[40480, 40482, 729, 2525, 10906, 485, 43, 8393...","[1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, ...",0,"[2683, 4969, 800, 5298, 840, 2499, 6632, 7022,..."
2,312329,120056,"[40480, 21044, 16954, 8294, 556, 10837, 40481]","[[5867, 24176], [1353], [6953], [1301, 11332],...","[40480, 40482, 8240, 481, 24176, 296, 1353, 66...","[0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, ...",1,"[1257, 7655, 6270, 590, 5024, 1119, 4883, 6696..."
3,74301,168258,"[40480, 10025, 31156, 40481]","[[1270, 1645, 28447], [21601], [27952, 29471, ...","[40480, 40482, 5539, 21601, 1073, 903, 2324, 4...","[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",0,"[7940, 3609, 7060, 6265, 1170, 6654, 5003, 3561]"
4,76272,109030,"[40480, 17841, 252, 782, 2373, 1641, 2373, 252...","[[1430, 11434], [1430, 17027], [1615, 23, 695,...","[40480, 40482, 14046, 1430, 11434, 488, 17027,...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, ...",0,"[3484, 6324, 7594, 243]"

In [7]:
raw_recipes = raw_recipes.rename(columns={'id':'recipe_id'}).loc[:,['recipe_id','ingredients', 'tags','nutrition','minutes','steps']]
pp_recipes = pp_recipes.rename(columns={'id':'recipe_id'}).loc[:,['recipe_id','techniques']]

recipes = raw_recipes.merge(pp_recipes, on='recipe_id', how='left').set_index('recipe_id')
recipes.head()

,ingredients,tags,nutrition,minutes,steps,techniques
recipe_id,,,,,,
137739,"[winter squash, mexican seasoning, mixed spice...","[60-minutes-or-less, time-to-make, course, mai...","[51.5, 0.0, 13.0, 0.0, 2.0, 0.0, 4.0]",55,"[make a choice and proceed with recipe, depend...","[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
31490,"[prepared pizza crust, sausage patty, eggs, mi...","[30-minutes-or-less, time-to-make, course, mai...","[173.4, 18.0, 0.0, 17.0, 22.0, 35.0, 1.0]",30,"[preheat oven to 425 degrees f, press dough in...","[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
112140,"[ground beef, yellow onions, diced tomatoes, t...","[time-to-make, course, preparation, main-dish,...","[269.8, 22.0, 32.0, 48.0, 39.0, 27.0, 5.0]",130,"[brown ground beef in large pot, add chopped o...",NaN
59389,"[spreadable cheese with garlic and herbs, new ...","[60-minutes-or-less, time-to-make, course, mai...","[368.1, 17.0, 10.0, 2.0, 14.0, 8.0, 20.0]",45,[place potatoes in a large pot of lightly salt...,"[1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, ..."
44061,"[tomato juice, apple cider vinegar, sugar, sal...","[weeknight, time-to-make, course, main-ingredi...","[352.9, 1.0, 337.0, 23.0, 3.0, 0.0, 28.0]",190,"[mix all ingredients& boil for 2 1 / 2 hours ,...",NaN

In [8]:
### TECHNIQUES ###
# Search through "steps" column to fill recipes with missing techniques

technique_list = ['bake','barbecue','blanch','blend','boil','braise','brine','broil','caramelize','combine','crock pot','crush','deglaze','devein','dice','distill',
    'drain','emulsify','ferment','freez','fry','grate','griddle','grill','knead','leaven','marinate','mash','melt','microwave','parboil','pickle','poach','pour',
    'pressure cook','puree','refrigerate','roast','saute','scald','scramble','shred','simmer','skillet','slow cook','smoke','smooth','soak','sous-vide','steam',
    'stew','strain','tenderize','thicken','toast','toss','whip','whisk']

recipes.loc[recipes['techniques'].isna(),'techniques'] = recipes.loc[recipes['techniques'].isna(),'steps'].apply(lambda x: [1 if t in ' '.join(x) else 0 for t in technique_list])
recipes.drop('steps',axis=1,inplace=True)

# Replace techniques one-hot-encoding with dictionary to make downstream usage easier
technique_list_cap = [i.title() if i != 'freez' else 'Freeze' for i in technique_list]
recipes['techniques'] = recipes['techniques'].apply(lambda x: {j:i for i,j in zip(x,technique_list_cap)})
recipes.head()

,ingredients,tags,nutrition,minutes,techniques
recipe_id,,,,,
137739,"[winter squash, mexican seasoning, mixed spice...","[60-minutes-or-less, time-to-make, course, mai...","[51.5, 0.0, 13.0, 0.0, 2.0, 0.0, 4.0]",55,"{'Bake': 1, 'Barbecue': 0, 'Blanch': 0, 'Blend..."
31490,"[prepared pizza crust, sausage patty, eggs, mi...","[30-minutes-or-less, time-to-make, course, mai...","[173.4, 18.0, 0.0, 17.0, 22.0, 35.0, 1.0]",30,"{'Bake': 1, 'Barbecue': 0, 'Blanch': 0, 'Blend..."
112140,"[ground beef, yellow onions, diced tomatoes, t...","[time-to-make, course, preparation, main-dish,...","[269.8, 22.0, 32.0, 48.0, 39.0, 27.0, 5.0]",130,"{'Bake': 0, 'Barbecue': 0, 'Blanch': 0, 'Blend..."
59389,"[spreadable cheese with garlic and herbs, new ...","[60-minutes-or-less, time-to-make, course, mai...","[368.1, 17.0, 10.0, 2.0, 14.0, 8.0, 20.0]",45,"{'Bake': 1, 'Barbecue': 0, 'Blanch': 0, 'Blend..."
44061,"[tomato juice, apple cider vinegar, sugar, sal...","[weeknight, time-to-make, course, main-ingredi...","[352.9, 1.0, 337.0, 23.0, 3.0, 0.0, 28.0]",190,"{'Bake': 0, 'Barbecue': 0, 'Blanch': 0, 'Blend..."

In [9]:
### NUTRITION ###
# Replace nutrition list with dictionary to make downstream usage easier
nutriKey =  ['calories', 'total fat', 'sugar', 'sodium', 'protein', 'saturated fat', 'carbohydrates']
nutriKey_cap = [i.title() for i in nutriKey]
recipes['nutrition'] = recipes['nutrition'].apply(lambda x: {j:i for i,j in zip(x,nutriKey_cap)})
recipes.head()

,ingredients,tags,nutrition,minutes,techniques
recipe_id,,,,,
137739,"[winter squash, mexican seasoning, mixed spice...","[60-minutes-or-less, time-to-make, course, mai...","{'Calories': 51.5, 'Total Fat': 0.0, 'Sugar': ...",55,"{'Bake': 1, 'Barbecue': 0, 'Blanch': 0, 'Blend..."
31490,"[prepared pizza crust, sausage patty, eggs, mi...","[30-minutes-or-less, time-to-make, course, mai...","{'Calories': 173.4, 'Total Fat': 18.0, 'Sugar'...",30,"{'Bake': 1, 'Barbecue': 0, 'Blanch': 0, 'Blend..."
112140,"[ground beef, yellow onions, diced tomatoes, t...","[time-to-make, course, preparation, main-dish,...","{'Calories': 269.8, 'Total Fat': 22.0, 'Sugar'...",130,"{'Bake': 0, 'Barbecue': 0, 'Blanch': 0, 'Blend..."
59389,"[spreadable cheese with garlic and herbs, new ...","[60-minutes-or-less, time-to-make, course, mai...","{'Calories': 368.1, 'Total Fat': 17.0, 'Sugar'...",45,"{'Bake': 1, 'Barbecue': 0, 'Blanch': 0, 'Blend..."
44061,"[tomato juice, apple cider vinegar, sugar, sal...","[weeknight, time-to-make, course, main-ingredi...","{'Calories': 352.9, 'Total Fat': 1.0, 'Sugar':...",190,"{'Bake': 0, 'Barbecue': 0, 'Blanch': 0, 'Blend..."

In [10]:
### CUISINE ###
# Pull cuisines from "tags" column for each recipe

tags = pd.read_csv(os.path.join(raw_path, 'tags.csv')).sort_values('tagsCount',ascending=False)
cuisine = tags.loc[tags['Category'] == 'cuisine', 'tags'].tolist()
# cuisine = [i.replace('-',' ') for i in cuisine]

def assign_cuisine(tag_list):
    for tag in tag_list:
        if tag in cuisine:
            return tag.replace('-',' ').title()
    return 'N/A'

recipes['cuisine'] = recipes['tags'].apply(lambda x: assign_cuisine(x))
print(f"{len(recipes.loc[recipes['cuisine']=='N/A',:])} recipes do not have a cuisine tag ({round(len(recipes.loc[recipes['cuisine']=='N/A',:])/len(recipes)*100,1)}%)")

129362 recipes do not have a cuisine tag (55.8%)

In [11]:
### MEAL_OF_DAY ### 
# Pull meal of day from "tags" column for each recipe

meal = tags.loc[tags['Category'] == 'meal', 'tags'].tolist()

def assign_meal(tag_list):
    for tag in tag_list:
        if tag in meal:
            return tag.replace('-',' ').title()
    return 'NO MEAL'

recipes['meal_of_day'] = recipes['tags'].apply(lambda x: assign_meal(x))
print(f"{len(recipes.loc[recipes['meal_of_day']=='NO MEAL',:])} recipes do not have a meal tag ({round(len(recipes.loc[recipes['meal_of_day']=='NO MEAL',:])/len(recipes)*100,1)}%)")

45399 recipes do not have a meal tag (19.6%)

In [12]:
### INGREDIENT MAP ###
# Use user created map to simplify recipe ingredients
ingrMap = pd.read_excel(os.path.join(raw_path, 'ingrMap_Matt.xlsx'), engine='openpyxl').loc[:,['ingredients','Matt_replaced']]
ingrReplaced = recipes[['ingredients']].reset_index().explode('ingredients').merge(ingrMap,on='ingredients',how='left')
ingrReplaced = ingrReplaced.groupby('recipe_id')['ingredients'].apply(list).reset_index().set_index('recipe_id')
recipes = recipes.drop('ingredients',axis=1).join(ingrReplaced).drop('tags',axis=1)

In [13]:
display(recipes.head())
yn = input('Do you want to save recipes_in file? (y or n): ')
if yn == 'y': 
    if os.path.isfile(os.path.join(clean_path,'recipes_in.parquet')):
        i = 1
        while os.path.isfile(os.path.join(clean_path,'archive','recipes_in_v'+str(i)+".parquet")):
            i+=1
        
        shutil.copyfile(os.path.join(clean_path,'recipes_in.parquet'), os.path.join(clean_path,'archive','recipes_in_v'+str(i)+".parquet"))
        recipes.to_parquet(os.path.join(clean_path, 'recipes_in.parquet'))

,nutrition,minutes,techniques,cuisine,meal_of_day,ingredients
recipe_id,,,,,,
137739,"{'Calories': 51.5, 'Total Fat': 0.0, 'Sugar': ...",55,"{'Bake': 1, 'Barbecue': 0, 'Blanch': 0, 'Blend...",North American,Side Dishes,"[winter squash, mexican seasoning, mixed spice..."
31490,"{'Calories': 173.4, 'Total Fat': 18.0, 'Sugar'...",30,"{'Bake': 1, 'Barbecue': 0, 'Blanch': 0, 'Blend...",North American,Breakfast,"[prepared pizza crust, sausage patty, eggs, mi..."
112140,"{'Calories': 269.8, 'Total Fat': 22.0, 'Sugar'...",130,"{'Bake': 0, 'Barbecue': 0, 'Blanch': 0, 'Blend...",N/A,Main Dish,"[ground beef, yellow onions, diced tomatoes, t..."
59389,"{'Calories': 368.1, 'Total Fat': 17.0, 'Sugar'...",45,"{'Bake': 1, 'Barbecue': 0, 'Blanch': 0, 'Blend...",N/A,Side Dishes,"[spreadable cheese with garlic and herbs, new ..."
44061,"{'Calories': 352.9, 'Total Fat': 1.0, 'Sugar':...",190,"{'Bake': 0, 'Barbecue': 0, 'Blanch': 0, 'Blend...",North American,NO MEAL,"[tomato juice, apple cider vinegar, sugar, sal..."

## recipes_in_filtered
Filter recipes used to only contain those with user positive user interaction

In [14]:
recipes_in = pd.read_parquet(os.path.join(clean_path, 'recipes_in.parquet'))
recipes_in_filtered = recipes_in.loc[recipes_in.index.isin(recipe_filt),:]

print(f"Length of raw recipes_in file: {len(recipes_in)}")
print(f"Length of filtered recipes_in file: {len(recipes_in_filtered)}")
recipes_in_filtered.head()

yn = input('Save recipes_in_filtered dataframe to clean data? (y or n): ')
if yn == 'y': 
    if os.path.isfile(os.path.join(clean_path,f'recipes_in_count{rating_count}_mean{rating_mean}.parquet')):
        i = 1
        while os.path.isfile(os.path.join(clean_path,'archive',f'recipes_in_count{rating_count}_mean{rating_mean}_v{i}.parquet')):
            i+=1
        
        shutil.copyfile(os.path.join(clean_path,f'recipes_in_count{rating_count}_mean{rating_mean}.parquet'), os.path.join(clean_path,'archive',f'recipes_in_count{rating_count}_mean{rating_mean}_v{i}.parquet'))
    recipes_in_filtered.to_parquet(os.path.join(clean_path, f'recipes_in_count{rating_count}_mean{rating_mean}.parquet'))
    recipes_in_filtered.to_parquet(os.path.join(product_path, f'recipes_in_count{rating_count}_mean{rating_mean}.parquet'))

Length of raw recipes_in file: 231637
Length of filtered recipes_in file: 48454

# nutrition

In [15]:
# Create DataFrame from nutrition column of recipes_in
recipes_in = pd.read_parquet(os.path.join(clean_path, 'recipes_in.parquet'))
nutrition = recipes_in['nutrition'].apply(pd.Series)
display(nutrition.head())
yn = input("Do you want to save website.csv file? (y or n): ")
if yn == 'y': nutrition.to_csv(os.path.join(product_path, 'nutrition.csv'))

,calories,carbohydrates,protein,saturated fat,sodium,sugar,total fat
recipe_id,,,,,,,
137739,51.5,4.0,2.0,0.0,0.0,13.0,0.0
31490,173.4,1.0,22.0,35.0,17.0,0.0,18.0
112140,269.8,5.0,39.0,27.0,48.0,32.0,22.0
59389,368.1,20.0,14.0,8.0,2.0,10.0,17.0
44061,352.9,28.0,3.0,0.0,23.0,337.0,1.0

# websites

In [16]:
# Create dataframe with recipe_id, recipe name and food.com link
website = pd.read_parquet(os.path.join(raw_path, 'raw_recipes.parquet')).loc[:,['id','name']].rename(columns={'id':'recipe_id'})
website['url'] = website['recipe_id'].apply(lambda x: "https://www.food.com/recipe/"+str(x))
website = website.set_index('recipe_id')
website.head()

,name,url
recipe_id,,
137739,arriba baked winter squash mexican style,https://www.food.com/recipe/137739
31490,a bit different breakfast pizza,https://www.food.com/recipe/31490
112140,all in the kitchen chili,https://www.food.com/recipe/112140
59389,alouette potatoes,https://www.food.com/recipe/59389
44061,amish tomato ketchup for canning,https://www.food.com/recipe/44061

In [17]:
# Clean recipe names
import re
import string
def clean_recipe_name(name):
    # print(name)
    if name:
        sub_str = re.sub(r'\s+',' ', name)
        sub_str = re.sub('\ss\s', '\'s ',name)
        if bool(sub_str):
            # print(sub_str)
            return string.capwords(sub_str)
        else: return string.capwords(name)
    else: return name

website['name'] = website['name'].apply(lambda x: clean_recipe_name(x))
display(website.head())

,name,url
recipe_id,,
137739,Arriba Baked Winter Squash Mexican Style,https://www.food.com/recipe/137739
31490,A Bit Different Breakfast Pizza,https://www.food.com/recipe/31490
112140,All In The Kitchen Chili,https://www.food.com/recipe/112140
59389,Alouette Potatoes,https://www.food.com/recipe/59389
44061,Amish Tomato Ketchup For Canning,https://www.food.com/recipe/44061

In [18]:
# Check random sample of urls generated above
import requests
for url in np.random.choice(website['url'],10):
    response = requests.get(url)
    if response.status_code != 200: print(f"{url} doesn't exist")

In [19]:
yn = input("Do you want to save website.csv file? (y or n): ")
if yn == 'y': website.to_csv(os.path.join(product_path,'website.csv'))